/* Majlis v9.3 — generate_catalogs.js
   Single source of truth: skills folders' SKILL.md frontmatter + agents files.
   Preserves harvested AR/ZH translations from previous catalog.
   Run: node tools/generate_catalogs.js */
const fs=require('fs'),path=require('path');
const ROOT=path.join(__dirname,'..');
const CATS={security:['🛡️','المسار الأمني','Security Pipeline'],council:['🏛️','أدوار المجلس','Council Playbooks'],science:['🔬','قواعد البيانات العلمية','Science Databases'],creative:['🎨','الإنتاج الإبداعي','Creative Production'],cloudflare:['☁️','Cloudflare','Cloudflare'],meta:['🧰','أدوات النظام','System Meta']};
/* ---------- mini frontmatter parser (handles our known shapes) ---------- */
function fm(text){
  text=text.replace(/\r\n/g,'\n');
  if(!text.startsWith('---'))return{};
  const end=text.indexOf('\n---',3);if(end<0)return{};
  const lines=text.slice(3,end).split('\n');const out={};let key=null;
  for(const ln of lines){
    const m=ln.match(/^([A-Za-z_-]+):\s?(.*)$/);
    if(m){key=m[1];let v=m[2].trim();
      if(v==='>'||v==='>-'){out[key]='';continue}
      if(/^".*"$/.test(v)||/^'.*'$/.test(v))v=v.slice(1,-1);
      if(/^\[.*\]$/.test(v))v=v.slice(1,-1).split(',').map(x=>x.trim().replace(/^["']|["']$/g,'')).filter(Boolean);
      out[key]=v;continue}
    if(key&&(ln.startsWith('  ')||ln==='')&&typeof out[key]==='string'){
      out[key]+=(out[key]?' ':'')+ln.trim()}
  }
  return out;
}
/* ---------- harvest AR/ZH from previous catalog ---------- */
const prev=fs.readFileSync(path.join(ROOT,'SKILLS_CATALOG.md'),'utf8');
const TR={};
for(const m of prev.matchAll(/^\| `([\w-]+)` \| ((?:.(?!\| ))*)\.? \| ([^|]*)\| ([^|]*)\|$/gm)){
  TR[m[1]]={ar:m[3].trim(),zh:m[4].trim()};
}
/* ---------- collect skills ---------- */
const skills=[];
for(const dir of fs.readdirSync(path.join(ROOT,'skills'),{withFileTypes:true})){
  if(!dir.isDirectory()||dir.name==='science_skills_common')continue;
  const f=path.join(ROOT,'skills',dir.name,'SKILL.md');if(!fs.existsSync(f))continue;
  const meta=fm(fs.readFileSync(f,'utf8'));
  skills.push({id:dir.name,...meta});
}
skills.sort((a,b)=>a.id.localeCompare(b.id));
/* ---------- emit SKILLS_CATALOG.md ---------- */
let out=`# 🧩 كتالوج المهارات — Skills Catalog (ثلاثي اللغة / Trilingual)\n\n> مولَّد آلياً من ترويسات المهارات الحقيقية (المصدر الوحيد للحقيقة). **${skills.length} مهارة منشورة ×4 منصات.**\n> Auto-generated by \`tools/generate_catalogs.js\` — do not hand-edit.\n`;
let total=0;
for(const [cat,[emoji,arCat,enCat]] of Object.entries(CATS)){
  const list=skills.filter(s=>s.category===cat);if(!list.length)continue;total+=list.length;
  out+=`\n## ${emoji} ${arCat} — ${enCat} (${list.length})\n\n| Skill | Owner | English | العربية | 中文 |\n|---|---|---|---|---|\n`;
  for(const s of list){
    const tr=TR[s.id]||{ar:'—',zh:'—'};
    out+=`| \`${s.id}\` | @${s.owner||'—'} | ${String(s.description||'').replace(/\|/g,'\\|')} | ${tr.ar} | ${tr.zh} |\n`;
  }
}
out+=`\n---\n\n**الإجمالي Total 总计: ${total}**\n`;
fs.writeFileSync(path.join(ROOT,'SKILLS_CATALOG.md'),out);
console.log('SKILLS_CATALOG.md:',total,'skills');
/* ---------- emit COUNCIL.md ---------- */
const ags=[];
for(const f of fs.readdirSync(path.join(ROOT,'agents')).filter(x=>x.endsWith('.md'))){
  const t=fs.readFileSync(path.join(ROOT,'agents',f),'utf8');const m=fm(t);
  const ar=(t.match(/\*\*بالعربية:\*\* (.*)/)||[])[1]||'';
  const head=t.match(/^# (.*?)\n/m)||[];ags.push({id:f.replace('.md',''),head:head[1]||f,div:m.division,temp:m.temperature,skills:m.skills||[],ar});
}
const DIVS=[['lead','🧭','Command & Strategy','القيادة والاستراتيجية'],['recon','🔍','Recon & Risk','الرصد والمخاطر'],['eng','⚙️','Builders','الهندسة'],['gate','🚦','Gates — QA · Security · Code','البوابات'],['exp','🎨','Experience & Identity','التجربة والهوية'],['know','📚','Knowledge & Memory','المعرفة والذاكرة']];
let c='# 🏛️ المجلس — Council of Forty\n\n> مولَّد آلياً من \`agents/*.md\`. كل مقعد ملف وكيل كامل بصلاحياته وأدواته وعقد مخرجاته.\n> Auto-generated by \`tools/generate_catalogs.js\`.\n';
for(const [d,e,en,ar] of DIVS){
  const list=ags.filter(a=>a.div===d).sort((x,y)=>x.id.localeCompare(y.id));c+=`\n## ${e} ${en} — ${ar} (${list.length})\n\n| Seat | Temperature | Reference skills |\n|---|---|---|\n`;
  for(const a of list)c+=`| ${a.head} · *${a.ar}* | ${a.temp} | ${a.skills.length?a.skills.map(s=>'\`'+s+'\`').join(' '):'—'} |\n`;
}
c+=`\n**Total seats: ${ags.length}**\n`;
fs.writeFileSync(path.join(ROOT,'COUNCIL.md'),c);
console.log('COUNCIL.md:',ags.length,'seats');
